# permissions for end users to view eipbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: eipbinding-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: virteip-operator
    app.kubernetes.io/part-of: virteip-operator
    app.kubernetes.io/managed-by: kustomize
  name: eipbinding-viewer-role
rules:
- apiGroups:
  - virteip.github.com
  resources:
  - eipbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - virteip.github.com
  resources:
  - eipbindings/status
  verbs:
  - get
